### ISSUE TITLE
大佬啊，抱歉打扰了，请问理符插件啥时候能用啊

### ISSUE THREAD

**Issue by LocoThea** [tssailzz8/MyPlugins#1]

**Comment by tssailzz8** [comment]
点下lifu界面的复制然后把你复制的东西给我我给你添加使用权

**Comment by LocoThea** [comment]
S375296F18AEEA3C31897ECF9142A41D5,谢谢大佬，辛苦大佬了

**Comment by jy210152** [comment]
> 点下lifu界面的复制然后把你复制的东西给我我给你添加使用权

S0E19BAAAB7DEEFA1F5F18E0A7C806B81拜托了刷佬，我什么都会做的QAQ
