### ISSUE TITLE
[GNB]XIVComboExpandedest 

### ISSUE THREAD

**Issue by gamer4eg** [tssailzz8/MyPlugins#1]
I immediately apologize for the fact that the text was generated by a google translator.
My idea is extremely simple.
AoE combo burst mode release.
Everything is set out in the picture.
![image](https://user-images.githubusercontent.com/23147230/129068159-e48b5cbb-f918-46b1-b593-c2267e03a3c4.png)

**Comment by tssailzz8** [comment]
For AOE, I think it's already very simple.I mainly simplify for raid.By the way,are you Chinese?

**Comment by gamer4eg** [comment]
No. I am Russian)
New technologies allow us to understand each other.
Well, an item in the settings for this would not hurt. This will speed up the passage of the daily dungeon roulette by 30 seconds)

**Comment by gamer4eg** [comment]
thx!
