### ISSUE TITLE
需要lifu激活的在这留号，一人一号

### ISSUE THREAD

**Issue by tssailzz8** [tssailzz8/MyPlugins#11]

**Comment by hualingmao** [comment]
S3797F3C13FAE9E38BD899EAA24F1196E

**Comment by shangxue12138** [comment]
SF64CD93DFD82C501044BC783820ED478

**Comment by idokee** [comment]
SA0BA714039F5C1B3D132EF0733B8B566

**Comment by Gaawaii** [comment]
SCA5625949464829E1F2D393A2A9BF2FD

**Comment by BaWWorld** [comment]
S25F622F50127CB1C641A9E5F9E8C3AD2

**Comment by 422303771** [comment]
SAF2FF4AB41E06BB44F3A116B89A90A74

**Comment by tmingyuan11** [comment]
SF53D863B51DF548B408A16F8F7DB4AEF

**Comment by PicarioPi** [comment]
S9517C66FA5309268611558AB2A134B0E

**Comment by Sylfii** [comment]
S898E0F3A756D242CBF4A9A9128D712D5

**Comment by lemonznn** [comment]
S9ABD07D5274CAAE86D8137F8FB6B5FC6

**Comment by Dalek233** [comment]
SAFD0A9E46D3E723906DEC213B66FD634

**Comment by stig141** [comment]
SCD9D93CADC271F0A05E724BEF015C115

**Comment by betalebetela** [comment]
SAAF9550DB5536825045CA501373EC652

**Comment by trifyh** [comment]
S2E2DB3EC52EF997339E8CCF9B0D2C2B5

**Comment by Tianning7015** [comment]
S16369D77D288343669C7FDBA8E714A9C

**Comment by fenghao19971** [comment]
SD9415F71934D6642095FA772BC799406

**Comment by cThana7os** [comment]
SF545A08BF32DBA04520D7FA652480C11

**Comment by Gin191** [comment]
S8174785DB6D8ED0427E7BE28AF882299
谢谢大佬
