### ISSUE TITLE
[GNB] Add more time for 2nd gnashing Fang combo after no-mersy burst

### ISSUE THREAD

**Issue by gamer4eg** [tssailzz8/MyPlugins#2]
Outside of ideal conditions, 10 seconds is often not enough for a full combo. I believe that the time window must be increased to 15 seconds. Since an incomplete combo leads to a loss of dps.

XIVComboPlugin/IconReplacer.cs 
935 line
` if (level >= 60 &&(WuQingCD.CooldownRemaining>15||(WuQingCD.CooldownRemaining <= 15 && HasBuff(GNB.Buffs.NoMercy))) )`

**Comment by gamer4eg** [comment]
And so that the plugin tries to adhere to the ideal rotation - increase ONLY the combo continuation window, but not the start window.

**Comment by tssailzz8** [comment]
https://github.com/tssailzz8/XIVComboPluginExpandedest/blob/45cdb3177de6bb7b53d4c68e4fdadc0f6a215e1e/XIVComboPlugin/IconReplacer.cs#L935 in this，i use 20.Are you think 15 is better?

**Comment by gamer4eg** [comment]
Start time of the 2nd gnashing Fang combo - leave 20 seconds
The window for its execution - make 15.
In my opinion.
And then I got tired of losing the last ability in a combo because of this timer because of the boss mechanic.
(In addition, this will not harm the rotation in any way. It is only important when the first combo ability was used and sent to cooldown)

**Comment by gamer4eg** [comment]
thx!
