### ISSUE TITLE
zoom可以增加一个相对转视角的功能吗？

### ISSUE THREAD

**Issue by susususuhanmo** [tssailzz8/MyPlugins#23]
刷佬你好，我是一名手柄玩家，感觉需要调头的时候摇杆转向实在太慢了，如果可以用zoom一键把视角转向背面就太方便了。
看了一下好像zoom提供的都是绝对的东西南北的方向，我觉得如果可以相对转视角会比较舒服，希望刷佬可以采纳！

**Comment by tssailzz8** [comment]
增加/zoom turn black
