### ISSUE TITLE
[GNB] Hypervelocity

### ISSUE THREAD

**Issue by gamer4eg** [tssailzz8/MyPlugins#9]
![image](https://user-images.githubusercontent.com/23147230/145797310-8719edbf-f157-4886-b3b6-caab68f85083.png)
Please add Hypervelocity ability to your default combo. (Burst Strike combo already has it)

**Comment by Nik-Potokar** [comment]
Will be adding it later today

Please look forward to it.

**Comment by gamer4eg** [comment]
And fix Cartridge logic plz. (GNB now has three cartridges after reaching level 88.)

**Comment by tssailzz8** [comment]
i dont have GNB in International Service，so i will do it later

**Comment by gamer4eg** [comment]
Just grab pieces of code from other combo plugins. There is already a burst combo logic for 3 cartridges.
And also add the use of Hypervelocity after Burst Strike.
GNB has minor changes in this update.

**Comment by gamer4eg** [comment]
Lol, in the latest version you have Fated Circle instead of Burst Strike in your base combo.
![image](https://user-images.githubusercontent.com/23147230/146546297-0abdc956-a4ee-4587-b82d-06217e149031.png)
